spring.application.name=coachpad

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/coach-padd
spring.datasource.username=postgres
spring.datasource.password=sahar123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Change le port pour éviter les conflits
server.port=8080

# Dossiers de stockage
coachpad.upload.dir=uploads/excels