spring.application.name=coachpad

# PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://dpg-d92gav99rddc738ic0tg-a.virginia-postgres.render.com:5432/coachpad?sslmode=require
spring.datasource.username=coachpad
spring.datasource.password=J5NZNeGh9yv1n40j4otu4dJxdVEjydni
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Change le port pour éviter les conflits
server.port=8088

# Dossiers de stockage
coachpad.upload.dir=uploads/excels

# JWT
jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Default seeder user
app.default-user.email=user@coachpad.com
app.default-user.password=password123