spring.application.name=coachpad

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/coach_BD
spring.datasource.username=postgres
spring.datasource.password=sahar123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Fixe un login/mot de passe pour Spring Security (dev)
spring.security.user.name=admin
spring.security.user.password=1234
spring.security.user.roles=ADMIN

# Change le port pour éviter les conflits
server.port=8080